/**
 * FutureDMS API
 * Premier Enterprise Dealership Management System
 *
 * OpenAPI spec version: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Charge {
    /**
     * Unique identifier for a charge
     */
    id?: string;

    /**
     * Internal | Customer | Warrantee
     */
    type?: string;

    /**
     * The amount of a charge or discount
     */
    amount?: number;

    /**
     * The unique identifier that references the charge source.  This unique identifier reference a source indicated by the sourceType
     */
    source?: string;

    /**
     * Part | Labor | Promotion
     */
    sourceType?: string;

}
